name: Test
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  test:
    name: test-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Test app
        run: bun test
